pingcap/tidb-dev-guide

.github/pull_request_template.md, CONTRIBUTING.md, README.md
This pull request adds two files for:
- pull request template, to help contributors summarize their contributions.
- contributing guide, to help contributors getting started with how to contribute to this repo.
=> .github: add pull request template and contributing guide

get-started/install-golang.md
=> get-started: add install golang

get-started/install-golang.md
- close #19 
Update go version in document to 1.16.
=> install-golang: go version should be 1.16

get-started/debug-and-profile.md
- close #xxxx
- to #xxxx
add section about debugging
=> get-started: add debug and profiling

contribute-to-tidb/code-style-and-quality-guide.md
Encourage using the newtype pattern.
- to #26
=> Encourage using the newtype pattern

contribute-to-tidb/review-a-pr.md
- close #27 
Add more content about PR review, and some of it are more TiDB specific.
=> contribute-to-tidb: update how to review a pr

README.md
fix allcontributors format in README that violated by https://github.com/zz-jason/tidb-dev-guide/commit/fae78bde4bac252f40b427d61fcdaaa843647cec
[render version](https://github.com/zz-jason/tidb-dev-guide/blob/207db7c3371eb52e0ef8fe9f95e57b4b5e8c51db/README.md)
=> fix: allcontributors format in README

contribute-to-tidb/code-style-and-quality-guide.md
- to #26
Add a section on values versus pointers
=> dev guide: values instead of pointers

get-started/setup-an-ide.md
change configure's description
=> change config description to avoid ambiguity

contribute-to-tidb/write-document.md
Add content of how to make contribution to docs/docs-cn repository.
Reference: [docs/CONTRIBUTING.md at master · pingcap/docs](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md)
- close #25
=> add how to make docs/docs-cn contribution

src/SUMMARY.md, src/project-management/introduction.md, src/project-management/release-train-model.md, src/project-management/tidb-release-management.md
- close #28 
Write down the first version of Release Train Model.
=> release-train-model: write down the first version

src/project-management/introduction.md
Fix spelling and simplify wording.
Tran -> Train, and simplified sentence.
=> Release train model minor

src/get-started/build-tidb-from-source.md
=> build-tidb-from-source: reduce unnecessary GOPATH

src/contribute-to-tidb/contribute-code.md, src/get-started/build-tidb-from-source.md
Fix starter issues link in [Contribute Code](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html)
- close #101 
Change starter issues link to https://github.com/pingcap/tidb/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
=> Starter issues link

src/get-started/install-golang.md
=> install-golang: grammar review

src/get-started/build-tidb-from-source.md
=> chore: fix typo

src/get-started/build-tidb-from-source.md, src/get-started/commit-code-and-submit-a-pull-request.md, src/get-started/debug-and-profile.md, src/get-started/setup-an-ide.md, src/get-started/write-and-run-unit-tests.md
=> get-started: integrate reviews

src/SUMMARY.md, src/contribute-to-tidb/introduction.md, src/contribute-to-tidb/miscellaneous-topics.md
- close #133
This PR adds a template. If there is more info just add to it.
=> add miscellaneous-topics.md

src/contribute-to-tidb/review-a-pr.md
=> refactor 'Review a Pull Request'

src/understand-tidb/session.md
Close https://github.com/pingcap/tidb-dev-guide/issues/54
Add initial docs for session
=> Add session docs

src/understand-tidb/1pc.md
- close #118
Added dev guide article for 1PC.
=> Add dev guide for 1PC

src/contribute-to-tidb/write-document.md
- Add v5.2 and v5.3 as versions
- Fix typo in github PR filter
=> write-document: add v5.2 and fix typo

src/contribute-to-tidb/contribute-code.md, src/contribute-to-tidb/make-a-proposal.md
=> add pr issue association rule

src/contribute-to-tidb/report-an-issue.md, src/project-management/release-train-model.md
=> add release information

src/project-management/release-train-model.md
=> upgrade 5.0 to 5.0.6

src/project-management/release-train-model.md
=> update for v5.4.0 and v6.0

src/get-started/write-and-run-unit-tests.md
Add a bit more details on how to run a single test case, also if it is not ported to testify.
=> Added more information on running a single test without testify

src/project-management/release-train-model.md
=> TiDB uses feature branch strategy now

src/SUMMARY.md, src/contribute-to-tidb/introduction.md, src/contribute-to-tidb/release-notes-style-guide.md
Add a release notes language style guide. Ref: https://github.com/pingcap/community/pull/639
=> contribute-to-tidb: add release notes language style guide

src/project-management/release-train-model.md
=> add v5.3.1

src/contribute-to-tidb/write-document.md, src/project-management/release-train-model.md
=> start v6.1

src/project-management/release-train-model.md
=> update to 5.2.4

src/get-started/install-golang.md
https://internals.tidb.io/t/topic/776
- close #xxxx
- to #xxxx
=> upgrade to Go 1.19

src/get-started/commit-code-and-submit-a-pull-request.md, src/get-started/write-and-run-unit-tests.md
- CI job trigger comments were outdated
- lack of bazel updating requests in PR creating section
- update the CI job trigger comments
- add requests to update bazel files
=> update documents about CI chapter

src/understand-tidb/parser.md
See also: https://github.com/pingcap/tidb/pull/31944
=> parser: Remove old doc reference

src/get-started/setup-an-ide.md
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
- close #226
=> update go parameters for unit test

src/get-started/setup-an-ide.md
=> setup-an-ide: add popluate run configuration for Vscode

src/contribute-to-tidb/write-document.md
Updated the outdated information in [Write Document - TiDB Development Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/write-document.html).
=> Update write-document.md to make it generic for different doc versions 

src/get-started/commit-code-and-submit-a-pull-request.md
- close #xxxx
- to #xxxx
add a document about how to set pre-commit.
=> support pre-commit

src/understand-tidb/lock-resolver.md
- close #116
Create dev guide for lock resolver.
However, though I finished this (and IMO this one is ready for review), maybe we should finish these before:
And I'll do some modification after each one finished.
=> Add dev guide for lock resolver

src/get-started/install-golang.md
- close #xxxx: There isn't an existent related issue. I don't think it's necessary to open a new one for this.
Updated go version in "[Get Started/Install Golang](https://pingcap.github.io/tidb-dev-guide/get-started/install-golang.html)".
=> Bump go version from 1.19 to 1.20

src/get-started/write-and-run-unit-tests.md
Fix #233
- close #xxxx
- to #xxxx
=> update "Write and run unit tests" chapter

src/contribute-to-tidb/cherrypick-a-pr.md
Fixes #234
- close #234
- to #xxxx
Update chapter about cherry-pick pull request since cherry-pick pull request service of `ti-srebot` is offline. And  unified to `ti-chi-bot`'s `cherry-pick` plugin
=> Update "Create cherry-pick pull requests automatically" chapter

src/contribute-to-tidb/review-a-pr.md
Fixes #235
Signed-off-by: wuhuizuo <wuhuizuo@126.com>
- close #xxxx
- to #xxxx
=> Update "Accepting pull requests" chapter

src/contribute-to-tidb/report-an-issue.md, src/contribute-to-tidb/review-a-pr.md
- close #xxxx
- to #xxxx
A few typos in chapter *Contribute to TiDB* got fixed.
=> Contribute to TiDB: fixed a few typos

src/understand-tidb/implementation-of-typical-operators.md
=> Add `implementation-of-typical-operators`

src/get-started/write-and-run-unit-tests.md
Most packages were moved into pkg folder by https://github.com/pingcap/tidb/pull/47123. The 'Running a single test' section needs to be updated based on that.
Updated the relevant package locations in 'Running a single test' section.
=> Running a single test: update package locations

src/understand-tidb/implementation-of-vectorized-execution.md
=> add  implementation-of-vectorized-execution

src/get-started/setup-an-ide.md
Recently, TiDB changed directory structure(https://github.com/pingcap/tidb/pull/47123). Becase of this,TiDB developer has to needs to be updated based on that.
Fixed GoLand configuration.
=> fix setup-an-ide

src/get-started/setup-an-ide.md
tidb-server path has been changed.
change tidb-server package path and dir path
=> Update pkg,dir path
